### PR TITLE
Fix : "Resource has been exhausted (e.g. check quota)" that may appear when using the Gemini-pro model

### PR DESCRIPTION
**Pull request by Rubuark**
Refer to https://ai.google.dev/models/gemini and change the model name to solve this problem.

### CODE REVIEW

**Comment by H0llyW00dzZ** [comment]
yeah it's better to use original model name instead of using alias

**Comment by Rubuark** [comment]
> yeah it's better to use original model name instead of using alias

using alias may cause this error, although you have not actually exhausted resources. I tried using other API Keys, and the problem remained. The most interesting thing is that the same Key does not cause this error when using the Gemini-vision model.

**Comment by H0llyW00dzZ** [comment]
> > yeah it's better to use original model name instead of using alias
> 
> using alias may cause this error, although you have not actually exhausted resources. I tried using other API Keys, and the problem remained. The most interesting thing is that the same Key does not cause this error when using the Gemini-vision model.

The alias might change in the future, which could cause errors. Therefore, it's better to use the original name instead of the alias. For the Gemini Pro version, here is the original name that I am aware of.


model name:
`gemini-1.0-pro-vision-latest`


image

**Comment by Rubuark** [comment]
> > > yeah it's better to use original model name instead of using alias
> > 
> > 
> > using alias may cause this error, although you have not actually exhausted resources. I tried using other API Keys, and the problem remained. The most interesting thing is that the same Key does not cause this error when using the Gemini-vision model.
> 
> 的别名将来可能会更改，这可能会导致错误。因此，最好使用原始名称而不是别名。对于Gemini Pro Vision，这是我所知道的原始名称。`gemini-pro-vision`
> 
> 型号名称： `gemini-1.0-pro-vision-latest`
> 
> 图像

However, the Gemini-vision model has not been updated for a long time. Now it does not even support multi-turn conversations. I hope the next update can bring the multi-turn conversations function.

**Comment by Rubuark** [comment]
> > > yeah it's better to use original model name instead of using alias
> > 
> > 
> > using alias may cause this error, although you have not actually exhausted resources. I tried using other API Keys, and the problem remained. The most interesting thing is that the same Key does not cause this error when using the Gemini-vision model.
> 
> The alias for `gemini-pro-vision` might change in the future, which could cause errors. Therefore, it's better to use the original name instead of the alias. For the Gemini Pro Vision, here is the original name that I am aware of.
> 
> model name: `gemini-1.0-pro-vision-latest`
> 
> image

However, the Gemini-vision model has not been updated for a long time. Now it does not even support multi-turn conversations. I hope the next update can bring the multi-turn conversations function.

**Comment by H0llyW00dzZ** [comment]
> > > > yeah it's better to use original model name instead of using alias
> > > 
> > > 
> > > using alias may cause this error, although you have not actually exhausted resources. I tried using other API Keys, and the problem remained. The most interesting thing is that the same Key does not cause this error when using the Gemini-vision model.
> > 
> > 
> > The alias for `gemini-pro-vision` might change in the future, which could cause errors. Therefore, it's better to use the original name instead of the alias. For the Gemini Pro Vision, here is the original name that I am aware of.
> > model name: `gemini-1.0-pro-vision-latest`
> > image
> 
> However, the Gemini-vision model has not been updated for a long time. Now it does not even support multi-turn conversations. I hope the next update can bring the multi-turn conversations function.

Yes, to be honest, I prefer the Gemini Pro Vision over the GPT-4 Vision, even though the Gemini Pro Vision hasn't been updated for a long time in relation to this.

- #4088

It would be great if the Gemini Pro Vision supported multi-turn conversations, similar to `Gemini 1.5 Pro (1 Million Tokens)`. I've been testing the `Gemini 1.5 Pro (1 Million Tokens)` feature such as videos, movies, and other content.

**Pull request closed without merging**
