### PR TITLE
add google api safety settings by Settings page

### PR DESCRIPTION
**Pull request by yeung66**
## problem

Google's Gemini API has [safety settings](https://ai.google.dev/gemini-api/docs/safety-settings) and will block some content that they think dangerous. 
Google supports setting a security filtering level to control the scope of filtering. The current security filtering level is hard-coded as BLOCK_ONLY_HIGH, which will only block content that Google deems highly likely to be unsafe. This hardcoded approach is not adjustable and lacks flexibility.

So an option for selecting the security filtering level has been added to the settings page. The default remains BLOCK_ONLY_HIGH, but users can now choose other security levels.

**related issues：**
- https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/4311
- https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/4592

## Summary by CodeRabbit

- **New Features**
  - Introduced configuration options for Google safety settings in the Settings UI. Users can now select a safety threshold from a dropdown list.
- **Improvements**
  - Enhanced safety settings management by integrating a new enum for Google safety thresholds, allowing more granular control over content filtering levels.
- **Localization**
  - Added localized titles and subtitles for Google safety settings in both Chinese and English.

### CODE REVIEW

**Comment by lioensky** [comment]
So,Has the feature of this security settings interface been implemented? Still not on the agenda?

**Comment by lloydzhou** [comment]
It has already been implemented
Will be included in the subsequent release plan

**Review by Dogtiti — CHANGES_REQUESTED** [review]
please resolve the conflict ~

**Comment by yeung66** [comment]
> please resolve the conflict ~

the conflict already resolved.

**Comment by yeung66** [comment]
After merging the main branch, I found a bug about generating the gemini request url.
It lacks `/api/google/` for the `isApp == false` situation and causes wrong call to `/v1beta/models/gemini-1.5-pro-latest:generateContent`. The right url should be `/api/google/v1beta/models/gemini-1.5-pro-latest:generateContent`. 

Therefor I had a extra commit to fix the [problem#5014](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/5014)

**Comment by Dogtiti** [comment]
@yeung66 some update for google ,please resolve again

**Comment by yeung66** [comment]
> @yeung66 some update for google ,please resolve again

done

**Review by Dogtiti — APPROVED** [review]

**Pull request merged**
