### PR TITLE
[Cherry Pick] Improve Github Issue Template

### PR DESCRIPTION
**Pull request by H0llyW00dzZ**
> [!NOTE]  
> Currently, Chinese language support is not available because it is still in beta.

### CODE REVIEW

**Comment by H0llyW00dzZ** [comment]
Demo: https://github.com/H0llyW00dzZ/ChatGPT-Next-Web/issues/new/choose

**Comment by fred-bf** [comment]
@H0llyW00dzZ it seems having some syntax issue in Chinese version

https://github.com/H0llyW00dzZ/ChatGPT-Next-Web/issues/new?assignees=&labels=enhancement&projects=&template=%E5%8A%9F%E8%83%BD%E5%BB%BA%E8%AE%AE.yml&title=%5BFeature+Request%5D%3A+

**Comment by H0llyW00dzZ** [comment]
> @H0llyW00dzZ it seems having some syntax issue in Chinese version
> 
> https://github.com/H0llyW00dzZ/ChatGPT-Next-Web/issues/new?assignees=&labels=enhancement&projects=&template=%E5%8A%9F%E8%83%BD%E5%BB%BA%E8%AE%AE.yml&title=%5BFeature+Request%5D%3A+

It's GitHub issue. 


The syntax has already been corrected:

image

**Comment by H0llyW00dzZ** [comment]
even english as well

image

**Pull request merged**
