### PR TITLE
Simplify [UI/UX] [Chat] [Front End] scrollDomToBottom

### PR DESCRIPTION
**Pull request by H0llyW00dzZ**
- [+] refactor(chat.tsx): improve smooth scrolling behavior in useScrollToBottom function

Issues:

- ChatGPTNextWeb#4019

### CODE REVIEW

**Comment by H0llyW00dzZ** [comment]
> [!NOTE]  
> This so smoothly unlike stupid `typescript` using `requestAnimationFrame`

**Comment by kyboi** [comment]
This works well, also allows scrolling back up while response is still streaming

**Comment by H0llyW00dzZ** [comment]
> This works well, also allows scrolling back up while response is still streaming. However, sometimes it won't keep scrolling down even if nothing was touched and the answer is still streaming in.

haven't improve yet, its very complexity because of codebase too large, I am still figure out to made it better

**Comment by kyboi** [comment]
If found it's the actual smooth scrolling that breaks this. If you make it immediately update the scrolling position it keeps scrolling down, unless the user scrolls back up.

See 4b3c41a4fd4fa293bffe0b9d0399d34d801e4e61 for an example

**Comment by H0llyW00dzZ** [comment]
> If found it's the actual smooth scrolling that breaks this. If you make it immediately update the scrolling position it keeps scrolling down, unless the user scrolls back up.
> 
> See [4b3c41a](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/commit/4b3c41a4fd4fa293bffe0b9d0399d34d801e4e61) for an example

wait I think I know how to improve it

**Comment by H0llyW00dzZ** [comment]
this a better one but not smoothly, can scroll up to 999999+ messages

https://imgur.com/hmmDqkt

**Comment by H0llyW00dzZ** [comment]
the custom hook:
```tsx
// Custom hook for debouncing a function
function useDebouncedEffect(effect: () => void, deps: any[], delay: number) {
  // Include `effect` in the dependency array for `useCallback`
  const callback = useCallback(effect, [effect, ...deps]);

  useEffect(() => {
    const handler = debounce(callback, delay);

    handler();

    // Cleanup function to cancel the debounced call if the component unmounts
    return () => handler.cancel();
  }, [callback, delay]); // `callback` already includes `effect` in its dependencies, so no need to add it here again.
}
```

**Pull request closed without merging**
