### PR TITLE
fix: 修复导出时字符乱码问题

### PR DESCRIPTION
**Pull request by greenjerry**
修复导出json和markdown时中文及其他utf8字符乱码问题

乱码原因：
charCodeAt方法返回值范围在0~65535，不能直接转为uint8array

修复方式：
把downloadAs方法中的writeBinaryFile改为writeTextFile，[参考文档](https://tauri.app/v1/api/js/fs/)

### CODE REVIEW

**Comment by H0llyW00dzZ** [comment]
no
thats wrong

**Comment by H0llyW00dzZ** [comment]
downloadAs literally must be use binary

**Comment by greenjerry** [comment]
> downloadAs literally must be use binary

Can you tell me why? I can pass the test on windows, macos, and web, including downloading json and markdown. The text field of the downloadAs method specifies that string is required, why cannot it be saved using writeTextFile?

**Comment by H0llyW00dzZ** [comment]
> > downloadAs literally must be use binary
> 
> Can you tell me why? I can pass the test on windows, macos, and web, including downloading json and markdown. The text field of the downloadAs method specifies that string is required, why cannot it be saved using writeTextFile?

if you replace `writeBinaryFile` it wouldn't work for another such as image

**Comment by H0llyW00dzZ** [comment]
its backend  unlike frontend

**Comment by H0llyW00dzZ** [comment]
also `writeText` it used to be copying a text, unlike `writeBinaryFile`

**Comment by greenjerry** [comment]
No, I didn't replace writeBinaryFile from the global perspective. The download image section is not in the downloadAs method, it is in line 491 of [exporter. tsx](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/blob/e1b065c74a06ae5850f8aa37a6c8b97ff842fc6c/app/components/exporter.tsx#L491). Therefore, I only replace the writeBinaryFile in the downloadAs method and it does not affect the image

Furthermore, I did not remove writeBinaryFile from global. d.ts, so writeBinaryFile is still available in the project

**Comment by bigYaoAmazing** [comment]
Without replacing writeBinaryFile, you can use ArrayBuffer as a bridge object, use Uint16Array to write data to ArrayBuffer, and use Uint8Array to wrap ArrayBuffer and pass it to writeBinaryFile

**Comment by H0llyW00dzZ** [comment]
> Without replacing writeBinaryFile, you can use ArrayBuffer as a bridge object, use Uint16Array to write data to ArrayBuffer, and use Uint8Array to wrap ArrayBuffer and pass it to writeBinaryFile

you smart that safe way

**Pull request merged**
