### PR TITLE
Feature/h0lly w00dz z updater

### PR DESCRIPTION
**Pull request by lloydzhou**
#### 💻 变更类型 | Change Type

- [x] feat    
- [ ] fix    
- [ ] refactor    
- [ ] perf    
- [ ] style    
- [ ] test    
- [ ] docs    
- [ ] ci    
- [ ] chore    
- [ ] build    

## Summary by CodeRabbit

- **New Features**
	- Enhanced version checking for updates using semantic version comparison.
	- Conditional display of an update button for users in specific client contexts.
	- New updater interface for improved update management.

- **User Interface Improvements**
	- Updated error messages and feedback for update operations in both English and Chinese locales.
	- Added user feedback strings for successful and failed updates.

- **Bug Fixes**
	- Improved accuracy in determining available updates.
	- Enabled dialog prompts for update notifications.

### CODE REVIEW

**Review by Dogtiti — APPROVED** [review]

**Comment by lloydzhou** [comment]
这里有一个别人之前的升级视频

**Comment by Dogtiti** [comment]
可以基于这个改吧？

**Comment by Dogtiti** [comment]
我看了pr

**Comment by lloydzhou** [comment]
当天这个pr，我已经按之前那个人的逻辑，改过一次，让测试，没测通。。。你再看看这个pr，你本地编译了，把自己版本改低一些看看有没有对应的弹窗之类的逻辑

**Review by Dogtiti — APPROVED** [review]

**Pull request merged**
