### PR TITLE
Modify the default value of "safety_setting_gemini"

### PR DESCRIPTION
**Pull request by daiaji**
Change the default value of "safety_setting_gemini" to the lowest.

Fix this fault.https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/4311

### CODE REVIEW

**Review by H0llyW00dzZ — CHANGES_REQUESTED** [review]
> [!TIP]
> Instead of using hardcoded values, you can make it configurable, similar to the payloads models.

**Comment by daiaji** [comment]
> Tip
> 
> Instead of using hardcoded values, you can make it configurable, similar to the payloads models.

To be honest, that's what I thought, but the default configuration would make it almost impossible to use Gemini because of Google's annoying censorship mechanism, and modifying values directly as a mitigation strategy is an acceptable strategy.

**Comment by H0llyW00dzZ** [comment]
> > Tip
> > Instead of using hardcoded values, you can make it configurable, similar to the payloads models.
> 
> To be honest, that's what I thought, but the default configuration would make it almost impossible to use Gemini because of Google's annoying censorship mechanism, and modifying values directly as a mitigation strategy is an acceptable strategy.

It's still not stable for other languages, I think, because I have never encountered that annoying issue.

**Comment by daiaji** [comment]
> > > Tip
> > > Instead of using hardcoded values, you can make it configurable, similar to the payloads models.
> > 
> > 
> > To be honest, that's what I thought, but the default configuration would make it almost impossible to use Gemini because of Google's annoying censorship mechanism, and modifying values directly as a mitigation strategy is an acceptable strategy.
> 
> It's still not stable for other languages, I think, because I have never encountered that annoying issue.

> Google Gemini recently made another bizarre mistake: if you’re under 18, Gemini won’t help you with C++ programming because C++ is “too dangerous” for minors.

**Comment by H0llyW00dzZ** [comment]
> > > > Tip
> > > > Instead of using hardcoded values, you can make it configurable, similar to the payloads models.
> > > 
> > > 
> > > To be honest, that's what I thought, but the default configuration would make it almost impossible to use Gemini because of Google's annoying censorship mechanism, and modifying values directly as a mitigation strategy is an acceptable strategy.
> > 
> > 
> > It's still not stable for other languages, I think, because I have never encountered that annoying issue.
> 
> > Google Gemini recently made another bizarre mistake: if you’re under 18, Gemini won’t help you with C++ programming because C++ is “too dangerous” for minors.

<p align="center">
  <b>get good get golang</b>
  <br>
  Gopher
</p>

**Comment by Dean-YZG** [comment]
BLOCK_NONE is a restricted enum, so i think it is better to use BLOCK_ONLY_HIGH

https://cloud.google.com/vertex-ai/generative-ai/docs/multimodal/configure-safety-attributes?hl=zh-cn

**Pull request closed without merging**
