### PR TITLE
fix the problem of error at download the screenshot picture when there are some pics in messages history

### PR DESCRIPTION
**Pull request by tomridder**
之所以报错是因为 消息记录中的图片不属于私域中的图片 ，需要在toPNG之前 用一个后台接口转换为私域的图片地址，然后toPNG则不会报错可以正常下载   #3553

下面是 修复后的功能截图

动物
快乐

### CODE REVIEW

**Comment by H0llyW00dzZ** [comment]
lgtm, sadly I can't cherry pick commit this branch because bug still not fixed yet

**Comment by tomridder** [comment]
> lgtm

i think it is solved ... you can add gpt-4v model and test it ...it is solved ...
these  pic tells everythong
下载

**Comment by tomridder** [comment]
it we don't add the transferimg api and there's the pics in the chat history , toPNG method will go some error because the pic don't belong to this domain .

that's why we need to add the transferimg api

**Comment by H0llyW00dzZ** [comment]
> it we don't add the transferimg api and there's the pics in the chat history , toPNG method will go some error because the pic don't belong to this domain .
> 
> that's why we need to add the transferimg api

yeah because of cors issue, been known it

**Comment by H0llyW00dzZ** [comment]
I cherry pick pr this to my fork
https://hackerchat.btz.sh/#/changelog

**Comment by Dean-YZG** [comment]
thanks a lot for your works, it's a good way to solve cross-domain problems, but it would lead to a ssrf

**Pull request closed without merging**
