### PR TITLE
fix: proper localstorage usage

### PR DESCRIPTION
**Pull request by SukkaW**
#### 💻 变更类型 | Change Type

- [ ] feat    
- [x] fix    
- [ ] refactor    
- [ ] perf    
- [ ] style    
- [ ] test    
- [ ] docs    
- [ ] ci    
- [ ] chore    
- [ ] build    

#### 🔀 变更说明 | Description of Change

image

I noticed a `ReferenceError: localStorage is not defined` error in my CI. The PR adds extra guards against `localStorage` access in the server/CI.

## Summary by CodeRabbit

- **New Features**
  - Introduced a new dependency, `foxact`, enhancing application functionality.

- **Improvements**
  - Simplified local storage management for language filtering, improving readability and maintainability.
  - Enhanced robustness of storage functions to prevent errors in non-browser environments.
  - Added new hooks and utility functions for improved state management in React applications.

- **Bug Fixes**
  - Updated handling of the absence of a language filter to ensure consistent representation across the application.

### CODE REVIEW

**Comment by lloydzhou** [comment]
我编译的时候看到这个报错信息了

但是这个并不影响整体逻辑，只是判断好组件在服务端运行导致的报错问题。

并不想因为这个引入额外的库

**Comment by SukkaW** [comment]
> 我编译的时候看到这个报错信息了
> 
> 但是这个并不影响整体逻辑，只是判断好组件在服务端运行导致的报错问题。
> 
> 并不想因为这个引入额外的库

The extra library is for `mask language` only. The `useState` + using `useEffect` as watch is just a bad React practice.

**Comment by lloydzhou** [comment]
image

鉴于前面提到的不想增加额外的包，这个pr里面应该，只有三个文件更改，不更改package.json以及yarn.lock
应该就没问题了

**Comment by SukkaW** [comment]
> a0f11bf

Done in [`a0f11bf` (#5382)](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/pull/5382/commits/a0f11bff319b311ad7c5987e328e4414610ea4b8)

**Comment by Dogtiti** [comment]
#5386

**Pull request closed without merging**
