### PR TITLE
[WIP] Feat DALL·E Models

### PR DESCRIPTION
**Pull request by H0llyW00dzZ**

### CODE REVIEW

**Comment by akmumu** [comment]
{
  "error": {
    "message": "You are not allowed to sample from this model",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}

**Comment by H0llyW00dzZ** [comment]
> { "error": { "message": "You are not allowed to sample from this model", "type": "invalid_request_error", "param": null, "code": null } }

this pr still wip

**Comment by akmumu** [comment]
> > { "error": { "message": "You are not allowed to sample from this model", "type": "invalid_request_error", "param": null, "code": null } }
> 
> this pr still wip

yeah

**Comment by iiitmahesh** [comment]
any update on this?

**Comment by lloydzhou** [comment]
duplicate #5173

**Pull request closed without merging**
