### PR TITLE
chore: update product name from`ChatGPT-Next-Web` to `NextChat`

### PR DESCRIPTION
**Pull request by fredliang44**
## Overview
This pull request addresses the issue [#3573](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/3573) reported in our repository. The problem is related to our application's product name, which seems to be triggering Chrome's blocking mechanisms.

## Changes
- Updated the product name in various files across the project to ensure consistency and to avoid potential blocks by Chrome.

## Impact
- This change should not affect the application's functionality but is expected to letting users aware the product name change.

## Request for Review
@Yidadaa , kindly review the changes to ensure alignment with our product standards and to confirm that this update addresses the issue effectively.

### CODE REVIEW

**Comment by YANG-Mingcong** [comment]
Could not understand why send this pull request  to main branch.... suggest @Yidadaa close this pull

**Comment by ChatGPTNextWeb** [comment]
We plan to change the name of this repo and avoid using the word ChatGPT to prevent some legal concerns. @Yidadaa was also agreed to this action.

**Comment by ChatGPTNextWeb** [comment]
Also, thank you for reviewing this PR! @YANG-Mingcong

**Comment by H0llyW00dzZ** [comment]
> Could not understand why send this pull request to main branch.... suggest @Yidadaa close this pull

it's optional, not really needed I guess, my domain still fine without changing name https://hackerchat.btz.sh/

**Pull request merged**
